services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports: ["5432:5432"]
  
  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: .
    ports: ["8000:8000"]
    depends_on: [db, redis]
