services:
  - type: web
    name: url-shortener-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_HOST
        fromService:
          type: redis
          name: url-shortener-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: url-shortener-redis
          property: port

databases:
  - name: url-shortener-db
    databaseName: urlshort
    user: urlshort
    plan: starter

redis:
  - name: url-shortener-redis
    plan: starter
